# Generated by Django 2.0.5 on 2020-08-14 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shucaiyidate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='XieYiAutoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('test_module', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('test_case_title', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('forcount', models.CharField(default='', max_length=100, verbose_name='循环次数')),
                ('time_delay', models.CharField(default='', max_length=100, verbose_name='次数间上报间隔（单位：秒）')),
                ('is_check_crc', models.BooleanField(default=True, verbose_name='是否进行CRC校验')),
                ('shebeiid', models.CharField(blank=True, default='01', help_text='请输入设备ID', max_length=100, null=True, verbose_name='设备ID')),
                ('gongnengma', models.CharField(blank=True, default='03', help_text='请输入功能码', max_length=100, null=True, verbose_name='功能码')),
                ('shujuchangdu', models.CharField(blank=True, default='123456', help_text='请输入数据长度', max_length=100, null=True, verbose_name='数据长度')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '模拟下发16进制数据工具',
                'verbose_name_plural': '模拟下发16进制数据工具',
            },
        ),
        migrations.CreateModel(
            name='XieYiOneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yinzi_code', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='因子编码')),
                ('yinzi_rtd_down', models.CharField(default='', max_length=100, verbose_name='因子数值_下限')),
                ('yinzi_rtd_up', models.CharField(default='', max_length=100, verbose_name='因子数值_上限')),
                ('yinzi_rtd_xiaoshuwei', models.CharField(default='6', help_text='浮点型数据固定设置为：6；整数设置为：0；', max_length=100, verbose_name='因子数值_小数位数')),
                ('yinzi_rtd_count', models.CharField(default='1', max_length=100, verbose_name='因子数值个数')),
                ('yinzi_zijiexu', models.CharField(default='1234', max_length=100, verbose_name='字节序')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
                ('xieyiautodata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shucaiyidate.XieYiAutoData', verbose_name='模拟下发16进制数据工具')),
            ],
            options={
                'verbose_name': '协议单个数据',
                'verbose_name_plural': '协议单个数据',
            },
        ),
    ]
