# Generated by Django 2.0.5 on 2020-05-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucaiyidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagcontent',
            name='config_project',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='项目名称'),
        ),
    ]
