# Generated by Django 2.0.5 on 2020-08-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shucaiyidate', '0002_xieyiautodata_xieyionedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xieyiautodata',
            name='shujuchangdu',
            field=models.CharField(blank=True, default='04', help_text='请输入数据长度', max_length=100, null=True, verbose_name='数据长度'),
        ),
    ]
