# Generated by Django 2.0.5 on 2020-05-21 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shucaiyidate', '0002_tagcontent_config_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagcontent',
            name='tag_father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shucaiyidate.TagContent', verbose_name='依赖的父节点'),
        ),
    ]
