# Generated by Django 2.0.5 on 2020-02-24 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0002_updatedbdata_write_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='updatedbdata',
            name='db_paixuziduan',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='排序字段名'),
        ),
        migrations.AddField(
            model_name='updatedbdata',
            name='db_qianjiwei',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='获取前几行数据'),
        ),
        migrations.AddField(
            model_name='updatedbdata',
            name='is_daoxu',
            field=models.BooleanField(default=True, verbose_name='是否倒序'),
        ),
    ]
