# Generated by Django 2.0.5 on 2020-03-06 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0004_auto_20200224_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_qianjiwei',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='获取前几条数据'),
        ),
    ]
