# Generated by Django 2.0.5 on 2020-07-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0002_pageloadtimereport_write_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdmStatic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_name', models.CharField(default='', max_length=50, verbose_name='人员')),
                ('rdm_year', models.CharField(default='', max_length=50, verbose_name='日志年限')),
                ('rdm_data_range', models.CharField(default='', max_length=20, verbose_name='日志周时间范围')),
                ('day_date', models.CharField(default='', max_length=20, verbose_name='日志日期')),
                ('is_week', models.BooleanField(default=False, verbose_name='是否周记')),
                ('day_task_name', models.CharField(default='', max_length=20, verbose_name='日志任务名称')),
                ('day_task_desc', models.TextField(default='', verbose_name='日志任务详情')),
                ('day_task_quse', models.TextField(default='', verbose_name='日志问题详情')),
                ('week_task_deck', models.TextField(default='', verbose_name='周任务简述')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'RDM日志统计',
                'verbose_name_plural': 'RDM日志统计',
            },
        ),
    ]
