# Generated by Django 2.0.5 on 2020-07-16 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0003_rdmstatic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdmstatic',
            name='day_task_name',
            field=models.CharField(default='', max_length=500, verbose_name='日志任务名称'),
        ),
    ]
