# Generated by Django 2.0.5 on 2020-07-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0004_auto_20200716_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rdmstatic',
            name='day_date',
            field=models.CharField(default='', max_length=50, verbose_name='日志日期'),
        ),
        migrations.AlterField(
            model_name='rdmstatic',
            name='rdm_data_range',
            field=models.CharField(default='', max_length=50, verbose_name='日志周时间范围'),
        ),
    ]
