# Generated by Django 2.0.5 on 2020-07-16 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0005_auto_20200716_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyRdmStatic',
            fields=[
            ],
            options={
                'verbose_name': 'RDM日志统计（去掉空内容）',
                'verbose_name_plural': 'RDM日志统计（去掉空内容）',
                'proxy': True,
                'indexes': [],
            },
            bases=('reportdatas.rdmstatic',),
        ),
    ]
