# Generated by Django 2.0.5 on 2020-07-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0008_auto_20200716_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='RdmConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rdm_url', models.CharField(default='http://192.168.8.98:2000/main.do', max_length=1000, verbose_name='RDM网址')),
                ('rdm_account', models.CharField(default='', max_length=50, verbose_name='RDM登录账号')),
                ('rdm_password', models.CharField(default='', max_length=50, verbose_name='RDM登录密码')),
                ('recode_year', models.CharField(default='', max_length=50, verbose_name='获取RDM日志年限')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'RDM日志统计配置',
                'verbose_name_plural': 'RDM日志统计配置',
            },
        ),
    ]
