# Generated by Django 2.0.5 on 2020-08-29 10:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapidatas', '0002_apirequestdata_write_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestAssert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_assert_type', models.CharField(blank=True, default='request_key', max_length=100, null=True, verbose_name='断言类型')),
                ('input_assert', models.CharField(blank=True, default='request_key', max_length=100, null=True, verbose_name='输入预期断言内容')),
                ('sql_assert', models.CharField(blank=True, default='request_key', max_length=100, null=True, verbose_name='数据库语句断言')),
                ('code_assert', models.CharField(blank=True, default='request_key', max_length=100, null=True, verbose_name='状态码断言')),
                ('time_assert', models.CharField(blank=True, default='request_key', help_text='断言小于等于输入的毫秒数则通过', max_length=100, null=True, verbose_name='响应时间断言（单位：毫秒）')),
                ('is_auto_input', models.BooleanField(default=False, verbose_name='是否自动输入键值对的值')),
                ('auto_input_type', models.CharField(blank=True, choices=[('1', '数字'), ('2', '字母'), ('3', '数字和字母'), ('4', '数字和字母和特殊符号'), ('5', '数字和字母和特殊符号和转义字符'), ('6', '汉字')], default='6', max_length=10, null=True, verbose_name='自动输入字符的类型')),
                ('auto_input_long', models.CharField(blank=True, default='300', help_text='字符的个数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='自动输入的字符的个数')),
                ('request_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='键值对的值')),
                ('is_with_time', models.BooleanField(default=False, verbose_name='是否带时间串')),
                ('is_check', models.BooleanField(default=False, verbose_name='是否进行验证')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('apirequestdata', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testapidatas.ApiRequestData', verbose_name='依赖的接口用例')),
            ],
            options={
                'verbose_name': '断言内容',
                'verbose_name_plural': '断言内容',
            },
        ),
        migrations.AddField(
            model_name='requestdatas',
            name='sql_assert',
            field=models.CharField(blank=True, default='request_key', max_length=100, null=True, verbose_name='查询数据库相应值语句'),
        ),
    ]
