# Generated by Django 2.0.5 on 2020-08-30 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapidatas', '0003_auto_20200829_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdatas',
            name='sql_assert',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testupdatadb.UpdateDbData', verbose_name='查询数据库语句依赖'),
        ),
    ]
