# Generated by Django 2.0.5 on 2020-05-06 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdatas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchandcheck',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='radioandreelectionlabel',
            name='editandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.EditAndCheck', verbose_name='依赖的修改场景'),
        ),
        migrations.AddField(
            model_name='radioandreelectionlabel',
            name='newaddandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='depend_click_case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的点击场景的用例'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='depend_new_add_and_check_case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景的用例'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='loginandcheck',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='editandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.EditAndCheck', verbose_name='依赖的修改场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='loginandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.LoginAndCheck', verbose_name='依赖的登录场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='newaddandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputfile',
            name='editandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.EditAndCheck', verbose_name='依赖的修改场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputfile',
            name='newaddandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputdatetime',
            name='editandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.EditAndCheck', verbose_name='依赖的修改场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputdatetime',
            name='newaddandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景'),
        ),
        migrations.AddField(
            model_name='iframebodyinputtext',
            name='editandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.EditAndCheck', verbose_name='依赖的修改场景'),
        ),
        migrations.AddField(
            model_name='iframebodyinputtext',
            name='newaddandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景'),
        ),
        migrations.AddField(
            model_name='editandcheck',
            name='depend_click_case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的点击场景的用例'),
        ),
        migrations.AddField(
            model_name='editandcheck',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='deleteandcheck',
            name='depend_click_case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的点击场景的用例'),
        ),
        migrations.AddField(
            model_name='deleteandcheck',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
        migrations.AddField(
            model_name='clickandback',
            name='depend_case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的前置用例'),
        ),
        migrations.AddField(
            model_name='clickandback',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writeuser', to=settings.AUTH_USER_MODEL, verbose_name='添加用例人'),
        ),
        migrations.AddField(
            model_name='asserttiptext',
            name='editandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.EditAndCheck', verbose_name='依赖的修改场景'),
        ),
        migrations.AddField(
            model_name='asserttiptext',
            name='loginandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.LoginAndCheck', verbose_name='依赖的登录场景'),
        ),
        migrations.AddField(
            model_name='asserttiptext',
            name='newaddandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景'),
        ),
    ]
