# Generated by Django 2.0.5 on 2020-04-11 20:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('testupdatadb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShangBaoShuJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('test_module', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('test_case_title', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('forcount', models.CharField(default='', max_length=100, verbose_name='循环次数')),
                ('time_delay', models.CharField(default='', max_length=100, verbose_name='次数间上报间隔（单位：秒）')),
                ('is_check_crc', models.BooleanField(default=True, verbose_name='是否进行CRC校验')),
                ('shujuduan_st', models.CharField(blank=True, default='21', help_text='请输入ST', max_length=100, null=True, verbose_name='数据段_系统编码ST')),
                ('shujuduan_cn', models.CharField(blank=True, default='2011', help_text='请输入CN', max_length=100, null=True, verbose_name='数据段_命令编码CN')),
                ('shujuduan_pw', models.CharField(blank=True, default='123456', help_text='请输入PW', max_length=100, null=True, verbose_name='数据段_访问密码PW')),
                ('mn_type', models.CharField(blank=True, choices=[('P0', '输入MN'), ('P1', 'SQL语句获取MN'), ('P2', '输入范围值自动生成MN')], default='P0', max_length=10, null=True, verbose_name='获取MN类型')),
                ('shujuduan_mn', models.CharField(blank=True, default='A220582_0001', help_text='请输入MN', max_length=100, null=True, verbose_name='数据段_站点唯一标识MN')),
                ('mn_auto_make_base', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='自动生成MN_连续固定部分')),
                ('mn_auto_make_down', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='自动生成MN_下限')),
                ('mn_auto_make_up', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='自动生成MN_上限')),
                ('mn_auto_make_interval', models.CharField(blank=True, default='1', max_length=100, null=True, verbose_name='自动生成MN_间隔')),
                ('shujuduan_flag', models.CharField(blank=True, default='9', help_text='请输入Flag', max_length=100, null=True, verbose_name='数据段_应答标志Flag')),
                ('shujuduan_cp_datatime_type', models.CharField(blank=True, default='shishi', help_text='如果模拟上报实时数据，请输入“shishi”；如果模拟小时数据，请输入“xiaoshi”', max_length=100, null=True, verbose_name='数据段_指令参数CP的DataTime类型')),
                ('dele_zidian', models.CharField(blank=True, default='', help_text='多个字段之间以英文半角逗号(,)隔开', max_length=1000, null=True, verbose_name='获取目标数据库中因子值对应表所有字段中需要删除的字段')),
                ('actual_data_count', models.CharField(default='2', help_text='例如上报一条数据，则目标数据库中会出现上报的报文，此处应该填写1；若上报一条数据后需要再上报一条数据，然后目标数据库中才会出现第一次上报的报文，则此处应该填写2；依次类推...', max_length=100, verbose_name='目标数据库中接收到报文需要进行报文的次数')),
                ('actual_data_delay_time', models.CharField(default='60', max_length=100, verbose_name='上报数据到数据库录入数据预估耗时（单位：秒）')),
                ('tcp_host', models.CharField(default='192.168.8.205', max_length=100, verbose_name='tcp主机IP')),
                ('tcp_port', models.CharField(default='57001', max_length=100, verbose_name='tcp主机端口号')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('actual_data_sql', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_actual_data_sql', to='testupdatadb.UpdateDbData', verbose_name='获取目标数据库中因子值依赖的SQL场景')),
                ('mn_sql', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_mn_sql', to='testupdatadb.UpdateDbData', verbose_name='获取MN依赖的数据库SQL语句场景')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '模拟上报数据工具',
                'verbose_name_plural': '模拟上报数据工具',
            },
        ),
        migrations.CreateModel(
            name='ShuJuYinZi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yinzi_code', models.CharField(default='', max_length=100, verbose_name='因子编码')),
                ('yinzi_rtd_down', models.CharField(default='', max_length=100, verbose_name='因子数值_下限')),
                ('yinzi_rtd_up', models.CharField(default='', max_length=100, verbose_name='因子数值_上限')),
                ('yinzi_rtd_xiaoshuwei', models.CharField(default='1', max_length=100, verbose_name='因子数值_小数位数')),
                ('yinzi_rtd_count', models.CharField(default='1', max_length=100, verbose_name='因子数值个数')),
                ('yinzi_flag', models.CharField(default='', max_length=100, verbose_name='因子标识')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('shangbaoshuju', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shangbaoshuju.ShangBaoShuJu', verbose_name='依赖的模拟上报数据工具')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '数据段_指令参数CP的因子',
                'verbose_name_plural': '数据段_指令参数CP的因子',
            },
        ),
        migrations.CreateModel(
            name='StoreSBShuJu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('test_module', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('test_case_title', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('test_start_time', models.CharField(default='', max_length=100, verbose_name='开始运行时间')),
                ('forcount', models.CharField(default='', max_length=100, verbose_name='循环次数')),
                ('time_delay', models.CharField(default='', max_length=100, verbose_name='次数间上报间隔（单位：秒）')),
                ('is_check_crc', models.BooleanField(default=True, verbose_name='是否进行CRC校验')),
                ('shujuduan_mn', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='数据段_站点唯一标识MN')),
                ('sb_yinzi', models.CharField(default='', max_length=5000, verbose_name='上报因子字符串')),
                ('sb_shuju', models.CharField(default='', max_length=5000, verbose_name='上报数据字符串')),
                ('sb_ret', models.CharField(default='', max_length=5000, verbose_name='tcp响应数据')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '模拟上报数据记录',
                'verbose_name_plural': '模拟上报数据记录',
            },
        ),
    ]
