# Generated by Django 2.0.5 on 2020-05-06 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shangbaoshuju', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testupdatadb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesbshuju',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='shujuyinzi',
            name='shangbaoshuju',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shangbaoshuju.ShangBaoShuJu', verbose_name='依赖的模拟上报数据工具'),
        ),
        migrations.AddField(
            model_name='shujuyinzi',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='actual_data_sql',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_actual_data_sql', to='testupdatadb.UpdateDbData', verbose_name='获取目标数据库中因子值依赖的SQL场景'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_sql',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_mn_sql', to='testupdatadb.UpdateDbData', verbose_name='获取MN依赖的数据库SQL语句场景'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
