# Generated by Django 2.0.5 on 2020-02-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesbshuju',
            name='shujuduan_mn',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='数据段_站点唯一标识MN'),
        ),
    ]
