# Generated by Django 2.0.5 on 2020-02-23 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0002_updatedbdata_write_user'),
        ('shangbaoshuju', '0002_storesbshuju_shujuduan_mn'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_sql',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='testupdatadb.UpdateDbData', verbose_name='依赖的数据库SQL语句场景'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_type',
            field=models.CharField(blank=True, choices=[('P0', '输入MN'), ('P1', 'SQL语句获取MN'), ('P2', '输入范围值自动生成MN')], default='P0', max_length=10, null=True, verbose_name='获取MN类型'),
        ),
    ]
