# Generated by Django 2.0.5 on 2020-02-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0004_auto_20200223_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_auto_make_base',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='自动生成MN_连续固定部分'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_auto_make_down',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='自动生成MN_下限'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_auto_make_interval',
            field=models.CharField(blank=True, default='1', max_length=100, null=True, verbose_name='自动生成MN_间隔'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='mn_auto_make_up',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='自动生成MN_上限'),
        ),
    ]
