# Generated by Django 2.0.5 on 2020-02-23 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0002_updatedbdata_write_user'),
        ('shangbaoshuju', '0005_auto_20200223_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangbaoshuju',
            name='actual_data_sql',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_actual_data_sql', to='testupdatadb.UpdateDbData', verbose_name='获取目标数据库中因子值'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='mn_sql',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_mn_sql', to='testupdatadb.UpdateDbData', verbose_name='获取MN依赖的数据库SQL语句场景'),
        ),
    ]
