# Generated by Django 2.0.5 on 2020-02-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0008_auto_20200224_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='actual_data_sql',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbsj_actual_data_sql', to='testupdatadb.UpdateDbData', verbose_name='获取目标数据库中因子值依赖的SQL场景'),
        ),
    ]
