# Generated by Django 2.0.5 on 2020-03-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0009_auto_20200224_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_cn',
            field=models.CharField(blank=True, default='', help_text='请输入CN', max_length=100, null=True, verbose_name='数据段_命令编码CN'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_flag',
            field=models.CharField(blank=True, default='', help_text='请输入Flag', max_length=100, null=True, verbose_name='数据段_应答标志Flag'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_mn',
            field=models.CharField(blank=True, default='', help_text='请输入MN', max_length=100, null=True, verbose_name='数据段_站点唯一标识MN'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_pw',
            field=models.CharField(blank=True, default='', help_text='请输入PW', max_length=100, null=True, verbose_name='数据段_访问密码PW'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_st',
            field=models.CharField(blank=True, default='', help_text='请输入ST', max_length=100, null=True, verbose_name='数据段_系统编码ST'),
        ),
    ]
