# Generated by Django 2.0.5 on 2020-03-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0010_auto_20200306_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_cn',
            field=models.CharField(blank=True, default='2011', help_text='请输入CN', max_length=100, null=True, verbose_name='数据段_命令编码CN'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_cp_datatime_type',
            field=models.CharField(blank=True, default='shishi', help_text='如果模拟上报实时数据，请输入“shishi”；如果模拟小时数据，请输入“xiaoshi”', max_length=100, null=True, verbose_name='数据段_指令参数CP的DataTime类型'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_flag',
            field=models.CharField(blank=True, default='9', help_text='请输入Flag', max_length=100, null=True, verbose_name='数据段_应答标志Flag'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_mn',
            field=models.CharField(blank=True, default='A220582_0001', help_text='请输入MN', max_length=100, null=True, verbose_name='数据段_站点唯一标识MN'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_pw',
            field=models.CharField(blank=True, default='123456', help_text='请输入PW', max_length=100, null=True, verbose_name='数据段_访问密码PW'),
        ),
        migrations.AlterField(
            model_name='shangbaoshuju',
            name='shujuduan_st',
            field=models.CharField(blank=True, default='21', help_text='请输入ST', max_length=100, null=True, verbose_name='数据段_系统编码ST'),
        ),
    ]
