# Generated by Django 2.0.5 on 2020-03-06 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0011_auto_20200306_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shangbaoshuju',
            name='test_start_time',
        ),
    ]
