# Generated by Django 2.0.5 on 2020-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0013_shangbaoshuju_actual_data_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangbaoshuju',
            name='actual_data_delay_time',
            field=models.CharField(default='300', max_length=100, verbose_name='上报数据到数据库录入数据预估耗时（单位：秒）'),
        ),
    ]
