# Generated by Django 2.0.5 on 2020-03-06 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0016_auto_20200306_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='shangbaoshuju',
            name='tcp_host',
            field=models.CharField(default='192.168.8.205', max_length=100, verbose_name='tcp主机IP'),
        ),
        migrations.AddField(
            model_name='shangbaoshuju',
            name='tcp_post',
            field=models.CharField(default='57001', max_length=100, verbose_name='tcp主机端口号'),
        ),
    ]
