# Generated by Django 2.0.5 on 2020-03-08 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shangbaoshuju', '0017_auto_20200306_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shangbaoshuju',
            old_name='tcp_post',
            new_name='tcp_port',
        ),
    ]
