# Generated by Django 2.0.5 on 2020-04-11 14:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_height', models.CharField(default=75, max_length=100, verbose_name='封面图高度')),
                ('img_width', models.CharField(default=75, max_length=100, verbose_name='封面图宽度')),
                ('front_cover_img', models.ImageField(blank=True, height_field='img_height', null=True, upload_to='report/%Y%m', verbose_name='封面图片', width_field='img_width')),
                ('video', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='视频连接')),
                ('down_load', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='下载连接')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '爬取数据查询',
                'verbose_name_plural': '爬取数据查询',
            },
        ),
    ]
