# Generated by Django 2.0.5 on 2020-04-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderdate',
            name='splider_title',
            field=models.CharField(blank=True, default='爬取数据', max_length=100, null=True, verbose_name='数据标题'),
        ),
    ]
