# Generated by Django 2.0.5 on 2020-04-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderdate',
            name='director',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='spiderdate',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='spiderdate',
            name='label',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='发行商'),
        ),
        migrations.AddField(
            model_name='spiderdate',
            name='star',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='演员'),
        ),
        migrations.AddField(
            model_name='spiderdate',
            name='studio',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='制作商'),
        ),
        migrations.AlterField(
            model_name='spiderdate',
            name='splider_title',
            field=models.CharField(blank=True, default='爬取数据', max_length=1000, null=True, verbose_name='数据标题'),
        ),
    ]
