# Generated by Django 2.0.5 on 2020-05-06 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiderdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spidervideo',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderstudio',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderstar',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderseries',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderlabel',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderhmtag',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderhmchapterimage',
            name='spiderhmchapterdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spiderdata.SpiderHMChapterData', verbose_name='章节'),
        ),
        migrations.AddField(
            model_name='spiderhmchapterimage',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderhmchapterdata',
            name='spiderhmbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spiderdata.SpiderHMBook', verbose_name='书目'),
        ),
        migrations.AddField(
            model_name='spiderhmchapterdata',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderhmbook',
            name='hm_area',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderHMArea', verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='spiderhmbook',
            name='hm_tag',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderHMTag', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='spiderhmbook',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderhmarea',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spidergenre',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderdownload',
            name='spiderdata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spiderdata.SpiderData', verbose_name='作品'),
        ),
        migrations.AddField(
            model_name='spiderdownload',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderdirector',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='director',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderDirector', verbose_name='导演'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='genre',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderGenre', verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='label',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderLabel', verbose_name='发行商'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='series',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderSeries', verbose_name='系列'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='star',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderStar', verbose_name='演员'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='studio',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderStudio', verbose_name='制作商'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
