# Generated by Django 2.0.5 on 2020-04-14 03:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiderdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='系列')),
                ('series_url', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='系列外部链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '系列',
                'verbose_name_plural': '系列',
            },
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='long_time',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='时长（分钟）'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='series',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderSeries', verbose_name='系列'),
        ),
    ]
