# Generated by Django 2.0.5 on 2020-04-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0002_spiderdate_splider_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderdate',
            name='front_cover_img',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='report/%Y%m/screenshots/', verbose_name='封面图片', width_field='img_width'),
        ),
    ]
