# Generated by Django 2.0.5 on 2020-04-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0002_auto_20200412_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderdate',
            name='prenum',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='编号'),
        ),
    ]
