# Generated by Django 2.0.5 on 2020-04-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0002_auto_20200414_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderdata',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='检查封面'),
        ),
        migrations.AddField(
            model_name='spiderdata',
            name='is_love',
            field=models.BooleanField(default=False, verbose_name='喜爱'),
        ),
    ]
