# Generated by Django 2.0.5 on 2020-04-18 11:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiderdata', '0003_auto_20200417_0511'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderHMArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hm_area', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='地区')),
                ('hm_area_url', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='地区外部链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '地区',
                'verbose_name_plural': '地区',
            },
        ),
        migrations.CreateModel(
            name='SpiderHMBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splider_url', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='爬取数据URL')),
                ('splider_title', models.CharField(blank=True, default='爬取漫画数据', max_length=1000, null=True, verbose_name='数据标题')),
                ('img_height', models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='封面图高度')),
                ('img_width', models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='封面图宽度')),
                ('front_cover_img', models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='', verbose_name='封面图片', width_field='img_width')),
                ('chapter_count', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='章节数')),
                ('is_love', models.BooleanField(default=False, verbose_name='喜爱')),
                ('is_check', models.BooleanField(default=False, verbose_name='检查封面')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '爬去的漫画书名',
                'verbose_name_plural': '爬去的漫画书名',
            },
        ),
        migrations.CreateModel(
            name='SpiderHMData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('splider_url', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='爬取数据URL')),
                ('splider_title', models.CharField(blank=True, default='爬取漫画数据', max_length=1000, null=True, verbose_name='数据标题')),
                ('img_height', models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='封面图高度')),
                ('img_width', models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='封面图宽度')),
                ('back_front_cover_img', models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='', verbose_name='补传封面图片', width_field='img_width')),
                ('front_cover_img', models.CharField(blank=True, max_length=1500, null=True, verbose_name='封面图片')),
                ('prenum', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='编号')),
                ('long_time', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='时长（分钟）')),
                ('is_love', models.BooleanField(default=False, verbose_name='喜爱')),
                ('is_check', models.BooleanField(default=False, verbose_name='检查封面')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('hm_area', models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderHMArea', verbose_name='地区')),
            ],
            options={
                'verbose_name': '爬取漫画数据查询',
                'verbose_name_plural': '爬取漫画数据查询',
            },
        ),
        migrations.CreateModel(
            name='SpiderHMTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hm_tag', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='类型')),
                ('hm_tag_url', models.CharField(blank=True, default='', max_length=1500, null=True, verbose_name='类型外部链接')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '类型',
                'verbose_name_plural': '类型',
            },
        ),
        migrations.AddField(
            model_name='spiderhmdata',
            name='hm_tag',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderHMTag', verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='spiderhmdata',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名'),
        ),
    ]
