# Generated by Django 2.0.5 on 2020-04-18 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0004_auto_20200418_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='spiderhmbook',
            options={'verbose_name': '爬取的漫画书', 'verbose_name_plural': '爬取的漫画书'},
        ),
    ]
