# Generated by Django 2.0.5 on 2020-04-13 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0004_auto_20200413_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderdata',
            name='director',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderDirector', verbose_name='导演'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='genre',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderGenre', verbose_name='类别'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='label',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderLabel', verbose_name='发行商'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='star',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderStar', verbose_name='演员'),
        ),
        migrations.AlterField(
            model_name='spiderdata',
            name='studio',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderStudio', verbose_name='制作商'),
        ),
    ]
