# Generated by Django 2.0.5 on 2020-04-18 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0006_auto_20200418_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderhmchapterdata',
            name='spiderhmbook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spiderdata.SpiderHMBook', verbose_name='书目'),
        ),
        migrations.AlterField(
            model_name='spiderhmbook',
            name='front_cover_img',
            field=models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='hanman/', verbose_name='封面图片', width_field='img_width'),
        ),
    ]
