# Generated by Django 2.0.5 on 2020-04-13 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0006_auto_20200413_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderdata',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='spiderdata',
            name='img_width',
        ),
    ]
