# Generated by Django 2.0.5 on 2020-04-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0007_auto_20200418_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='back_front_cover_img',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='front_cover_img',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='img_width',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='is_check',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='is_love',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='long_time',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='prenum',
        ),
        migrations.AddField(
            model_name='spiderhmbook',
            name='hm_area',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderHMArea', verbose_name='地区'),
        ),
        migrations.AddField(
            model_name='spiderhmbook',
            name='hm_tag',
            field=models.ManyToManyField(blank=True, default='', to='spiderdata.SpiderHMTag', verbose_name='类型'),
        ),
    ]
