# Generated by Django 2.0.5 on 2020-04-13 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0007_auto_20200413_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderdownload',
            name='director_url',
        ),
        migrations.RemoveField(
            model_name='spidervideo',
            name='director_url',
        ),
    ]
