# Generated by Django 2.0.5 on 2020-04-18 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0008_auto_20200418_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='hm_area',
        ),
        migrations.RemoveField(
            model_name='spiderhmchapterdata',
            name='hm_tag',
        ),
    ]
