# Generated by Django 2.0.5 on 2020-04-18 14:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spiderdata', '0009_auto_20200418_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderHMChapterImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_title', models.CharField(blank=True, default=75, max_length=1000, null=True, verbose_name='图片标题')),
                ('img_height', models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='图片高度')),
                ('img_width', models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='图片宽度')),
                ('content_img', models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='hanman/content/', verbose_name='图片', width_field='img_width')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('spiderhmchapterdata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='spiderdata.SpiderHMChapterData', verbose_name='章节')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '漫画内容',
                'verbose_name_plural': '漫画内容',
            },
        ),
        migrations.AlterField(
            model_name='spiderhmbook',
            name='front_cover_img',
            field=models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='hanman/fengmian/', verbose_name='封面图片', width_field='img_width'),
        ),
    ]
