# Generated by Django 2.0.5 on 2020-04-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0009_auto_20200413_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spiderdata',
            name='back_front_cover_img',
            field=models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='', verbose_name='补传封面图片', width_field='img_width'),
        ),
    ]
