# Generated by Django 2.0.5 on 2020-04-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0010_auto_20200413_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderstar',
            name='back_start_photo',
            field=models.ImageField(blank=True, height_field='img_height', max_length=2000, null=True, upload_to='', verbose_name='补传演员头像', width_field='img_width'),
        ),
        migrations.AddField(
            model_name='spiderstar',
            name='img_height',
            field=models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='封面图高度'),
        ),
        migrations.AddField(
            model_name='spiderstar',
            name='img_width',
            field=models.CharField(blank=True, default=75, max_length=100, null=True, verbose_name='封面图宽度'),
        ),
    ]
