# Generated by Django 2.0.5 on 2020-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0010_auto_20200418_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderhmchapterdata',
            name='chapter_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='章节数'),
        ),
    ]
