# Generated by Django 2.0.5 on 2020-04-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderdata', '0011_spiderhmchapterdata_chapter_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderhmchapterimage',
            name='chapter_image_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='图片编号'),
        ),
    ]
